### ISSUE TITLE
MailChimp "welcome email" not sent when users are added to list

### ISSUE THREAD

**Issue by dberz** [strangerstudios/pmpro-mailchimp#11]
I've integrated different membership sign ups with various mailchimp lists.  Users are added to lists correctly.  Unfortunately, users do not receive the "final welcome email" for the lists when they are added, regardless of the checkbox setting for this feature in the mailchimp admin.

Is there a known issues with disabling the welcome email even if enabled within the mailchimp admin?

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
