### ISSUE TITLE
SSL CA cert issue

### ISSUE THREAD

**Issue by sagarbquicsolv** [strangerstudios/pmpro-mailchimp#12]
I want to integrate this plugin with PMPro, but when i enter my API key, i get this following error.

"Sorry, but MailChimp was unable to verify your API key. MailChimp gave this response:

API call to helper/ping failed: Problem with the SSL CA cert (path? access rights?)
Please try entering your API key again."

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
