### ISSUE TITLE
Sorry, but MailChimp was unable to verify your API key. 

### ISSUE THREAD

**Issue by Mdmoisell** [strangerstudios/pmpro-mailchimp#13]
Hi, this plugin has been working on my site for some time, but a couple of days ago I believe it stopped. My API seems to be fine otherwise. Can you help? Thank you.

Sorry, but MailChimp was unable to verify your API key. MailChimp gave this response:
We received an unexpected error: null
Please try entering your API key again.

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
