### ISSUE TITLE
Not sending all registrations

### ISSUE THREAD

**Issue by rungotell** [strangerstudios/pmpro-mailchimp#16]
Is there something up with the current version? It's only sending one or two of the registrations properly out of dozens.

**Comment by rungotell** [comment]
Is anyone even looking at this stuff?

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
