### ISSUE TITLE
Not Working with [pmpro_signup] 

### ISSUE THREAD

**Issue by somendrakm** [strangerstudios/pmpro-mailchimp#17]
Plugin is not working with Paid Memberships Pro - Register Helper Add On shortcode [pmpro_signup].

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
