### ISSUE TITLE
Merg fields invalid

### ISSUE THREAD

**Issue by elonden** [strangerstudios/pmpro-mailchimp#21]
When a new user subscribes it is not added to the corresponding mailchimp lists.

Mailchimp returns an error showing:

```
2016-04-15 17:51:05 GMT 
    nope    173.254.28.58   PUT /lists/.../members/.../ php 0.108s  WordPress/pmpro_addon_mc;http:  3.0 Your merge fields were invalid. 

```

I now need to manually add new members into the mailing list.

Using 
WP: 4.4.2
PMP: 1.8.9
Mailchimp Addon: 2.0.1

**Comment by cullanisthebest** [comment]
I'm having the same issue, anybody resolve this??

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
