### ISSUE TITLE
2.1 fails to sync with Mailchimp

### ISSUE THREAD

**Issue by ul8** [strangerstudios/pmpro-mailchimp#29]
Since updating to 2.1 adding people to a membership plan fails to  sync with mailchip.

Rolling back to 2.0.3 fixed the issue for me (just replaced the plugin files, no DB rollback)

I'm running Wordpress 4.7.5 with PMP 1.9.3

Let me know if I can help debugging this.

**Comment by andrewlimaza** [comment]
This may be linked with the following error -> 

Missing argument 3 for pmpromc_pmpro_mailchimp_listsubscribe_fields() in /home/sudsol5/public_html/member/wp-content/plugins/pmpro-mailchimp/pmpro-mailchimp.php on line 1307

This error occurs when editing user profiles.

**Comment by eighty20results** [comment]
Should be fixed in v2.1.1

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
