### ISSUE TITLE
Fails to sync

### ISSUE THREAD

**Issue by davehoward23** [strangerstudios/pmpro-mailchimp#34]
I have no idea if this is a conflict with any of the PMPRO add-ons I have running - I suspect it might be the Register Helper, however I need to be able to capture First Name and Last Name.

Simply put ---
The Mailchimp sync doesn't work.
Lists appear okay for all levels,
They just don't sync.

This doesn't make me want to sign up for a paid account!

**Comment by eighty20results** [comment]
Should be fixed in v2.1.1

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
