### ISSUE TITLE
After Registering a new Member Mailchimp not adding to the list

### ISSUE THREAD

**Issue by davesuy** [strangerstudios/pmpro-mailchimp#35]
I checked the checkbox saying "Join our mailing list." and I successfully registered to the site. But on the Mailchimp the new user is not added to the list.

**Comment by patidarkishor777** [comment]
I am getting same issue. I checked plugin setting and everything is fine with setting.

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
