### ISSUE TITLE
Fatal Error when adding API key

### ISSUE THREAD

**Issue by Bobz-zg** [strangerstudios/pmpro-mailchimp#36]
Fatal error: Call to a member function get_error_message() on array in /plugins/pmpro-mailchimp/includes/class.mailchimp.api.php on line 122

**Comment by eighty20results** [comment]
Should be fixed in v2.1.1

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
