### ISSUE TITLE
Feature Request:  Make level specific Opt-In Lists

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/pmpro-mailchimp#41]
Currently, the selected opt-in lists will show for all membership levels. This could be updated to show the opt-in lists based on levels as well. The ideal solution would be a modification to the GUI where lists can be specified as "opt-in" or "automatically subscribed to" for each level.

A more immediate solution could be to filter the opt-in lists in the `pmpromc_additional_lists_on_checkout()` function.

**Comment by dparker1005** [comment]
This kind of behavior can be implemented by automatically subscribing users to audiences when they receive a membership level, but then also using the "Double Opt-In" feature so that they are given the option of whether to opt-in after checkout.

We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
