### ISSUE TITLE
Expired members are not removed from MailChimp lists.

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/pmpro-mailchimp#43]
Expired members remain in MailChimp lists. Merge tags such as: PMPLEVELID, PMPALLIDS, PMPLEVEL also remain. Canceling a member in PMPro, works correctly, and results in removal from the list.

**Comment by ideadude** [comment]
> Expired members remain in MailChimp lists.

Need steps to recreate this. In particular, what are the settings for "remove members from old lists"?

> Merge tags such as: PMPLEVELID, PMPALLIDS, PMPLEVEL also remain.

We only set these when a user is subscribed to a list.

https://github.com/strangerstudios/pmpro-mailchimp/blob/master/pmpro-mailchimp.php#L972

So if you only get unsubscribed from everything, there is no push to MailChimp to update these fields.

Can we pass merge fields to the unsubscribe call here? https://github.com/strangerstudios/pmpro-mailchimp/blob/master/pmpro-mailchimp.php#L1050

Should we make a separate call? If so, let's only do that if we know we're not going to make a call to subscribe later.

**Comment by ideadude** [comment]
Also, users might switch levels, but if the levels are set to subscribe to the same lists then we won't subscribe OR unsubscribe the users. In this case, we want to update the merge fields as well.

Note. We do something similar when a user changes their email. We can piggy back on that code/API methods.

**Comment by gnpwdr-mike** [comment]
Bumping this. We're having this issue. Thanks!

**Comment by gnpwdr-mike** [comment]
Hi - Just checking in to see if this bug was ever addressed. Thanks!

**Comment by marvinschroeder** [comment]
We're having this issue too! Please fix this..

**Comment by messica** [comment]
To avoid throttling, we can POST to lists/{list_id} to batch subscribe and unsubscribe users with only 1 request to MailChimp's API: https://developer.mailchimp.com/documentation/mailchimp/reference/lists/#create-post_lists_list_id
> Up to 500 members may be added or updated with each API call.

However, this would be doing things a bit differently than the plugin currently works, so things might get out of sync if we don't address https://github.com/strangerstudios/pmpro-mailchimp/issues/50 at the same time -- right now, we actually DELETE the users to unsubscribe instead of updating their subscription status like MailChimp recommends.

**Comment by tictag** [comment]
Is there any update on this? I too am having this problem. We send member-only newsletters out using MailChimp so when a membership expires, they are, by default, still receiving member-only content. Manual intervention is required.

From the comments above, it looks like we're over-complicating this. Surely it would be easier to just change the 'Marketing Status' to 'Nonsubscribed' when a membership expires. If the customer then wishes to move the contact to a different audience or archive the contact, that's up to them, at least they won't receive member-only content when their membership expires.

If the member then renews, all you have to do is change their 'Marketing Status' back to 'Subscribed'.

_Note1: the MailChimp add-on should NEVER delete or archive a contact - doing this has serious implications for the customer (see https://mailchimp.com/help/delete-contacts/)_
_Note2: the MailChimp add-on should not mark the contact as 'Unsubscribed' because PMPro will no longer then be able to update the contact - only the contact themselves should 'Unsubscribe'._

**Comment by tictag** [comment]
Any update on this?

**Comment by dparker1005** [comment]
This issue should have been resolved in recent versions of PMPro Mailchimp. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
