### ISSUE TITLE
Just stopped working

### ISSUE THREAD

**Issue by kevinorin** [strangerstudios/pmpro-mailchimp#45]
I migrated from Digital Ocean to WP-Engine and PMP MailChimp add-on just stopped working. No users are added to associated lists after signup.

**Comment by mad2kx** [comment]
Same issue here since adding PMPRO WooCommerce integration

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
