### ISSUE TITLE
Bug: Users are not being cancelled from MailChimp when they are unsubscribed at the payment gateway.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-mailchimp#49]
Users are not being cancelled from MailChimp when they are unsubscribed at the payment gateway.
This is happening because we are only processing the $pmpromc_users_to_unsubscribe queue when redirecting to another page. Webhook, IPN handlers, etc. do not redirect so the queue does not get processed.

https://github.com/strangerstudios/pmpro-mailchimp/blob/f108de00dbb0d2f69bf0ff513df7d074017c0019/pmpro-mailchimp.php#L1092-L1093

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/mailchimp-unsubscribe-failing-with-stripe-failed-payments/

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported that should have fixed this bug. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
