### ISSUE TITLE
Bug: Not working with Add Member, WooCommerce Add Ons

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-mailchimp#52]
The Add On is not subscribing new members created with the Add Member Add On. This is probably due to the way subscriptions are queued and later processed during redirects which might be affecting other Add Ons and functionality as well.

**Comment by messica** [comment]
This is also affecting PMPro WooCommerce.

**Comment by ideadude** [comment]
template_redirect doesn't run in the dashboard?

https://github.com/strangerstudios/pmpro-mailchimp/blob/master/pmpro-mailchimp.php#L1092

So if a form is submitted and doesn't call wp_redirect (which we also hook into) the subs and unsubs never happen.

We need to hook into something else for the dashboard. The idea is to hook in as late as possible before the page loads.

**Comment by ideadude** [comment]
Maybe use this: https://codex.wordpress.org/Plugin_API/Action_Reference/shutdown

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported that should have fixed this bug. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
