### ISSUE TITLE
PMPRO LEVEL not added to the mailchimp list.

### ISSUE THREAD

**Issue by thanat** [strangerstudios/pmpro-mailchimp#56]
I'm using the PMPRO plugin (Version 2.0.5) and PMPRO mailchimp integration addon (Version 2.1.1).

The subscription to newsletter upon checkout is working but no PMPEVELID is submitted. 
I can see the entry inside Mailchimp but without the PMPLEVEL or PMPLEVELID values.

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported that should have fixed this bug. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
