### ISSUE TITLE
Users are Not added to Non-member Users	list after their membership expired

### ISSUE THREAD

**Issue by himanshuahuja96** [strangerstudios/pmpro-mailchimp#73]
User is getting archived from the old list but they are not being added to the Non-Members list which is configured.

Also, I saw the issue which says that the user is not archived from the expired level #43 list. But I have tested like with 3 accounts and they are getting removed.

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported that should have fixed this bug. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
