### ISSUE TITLE
Plugin Error Blank

### ISSUE THREAD

**Issue by hurricaneharrison** [strangerstudios/pmpro-mailchimp#8]
Hi there, for the latest version of PMPPro Mailchimp 1.0.6, when activated with version of WP 4.0.1 does not activate properly ... just simply leaves a blank white screen. Any ideas on potential incompatibility?

**Comment by totallyrich** [comment]
I've just installed the latest version of this plugin from the WordPress repo and when I activated it I received an error: "Plugin does not have a valid header". 

The plugin doesn't activate. 

I am using the latest version of WP 4.1

Any Ideas?

**Comment by totallyrich** [comment]
Ignore me. It did fail but I tried activating it again and it seems to work fine. Must have been a connectivity issue.

**Comment by stuartxt** [comment]
Installed on WP 4.3
PMPPro Mailchimp 1.0.7
Clicking on PMPro MailChimp link results in a blank page. The plugin also interferes with the member checkout page in that there is a conflict in the javascript resulting in the form submit button not being visible.

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
