### ISSUE TITLE
Improved logging

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/pmpro-mailchimp#81]
There's a few ways in which debug logging can be better:

1. Adding audience name in debug log instead of just audience ID. This would be pretty straightforward to implement, but every time we want to display the Audience names, we perform an API call to Mailchimp in order to get them as the audience names are currently not stored anywhere on the website. It may be worth caching that API call, in which case making this change in the debug log would essentially be free.

2. Improved error reporting. Currently, if Mailchimp does not send back a 200 OK status code, the error message is dumped. This part is a bit problematic since that error code relates to the API request as a whole, but since this is a batch update API, an individual audience member update can fail but the API request as a whole can return 200 (I've seen this when I've hit the Mailchimp API limit for a single email while testing). In the future, there should be better parsing of the response, even if it is 200 OK, to ensure that every audience member update was successfully processed as well. But again, the thing that makes this difficult is the batch processing that we've switched to in order to avoid overwhelming Mailchimp.

3. Outputting debug log to a separate file

Customer ticket (admins only): https://www.paidmembershipspro.com/forums/topic/bug-mailchimp-add-on-logs-not-created-after-update-to-mailchimp-add-on-v2-2/

**Comment by tictag** [comment]
RE (1.) ... the audience names are displayed in the Mailchimp Integration Options and Settings (../wp-admin/options-general.php?page=pmpromc_options). I guess these are stored somewhere? Better to get data from the database rather than generate a new API call?

RE (3.) ... I would suggest an optional 'enhanced debugging' user configurable option with standard logging going to WP_DEBUG, enhanced logging i.e. the full API call/response details, going to ../wp-content/plugins/paid-memberships-pro/logs per IPN debugging log (i.e. IPN.txt).

**Comment by tictag** [comment]
RE (2.) ... the complexities are a bit beyond me but the log could be very simply improved by making it it clear whether the log entry is what PMPro is sending or what it has received e.g. "Sending update to MailChimp...", "Received from MailChimp...".

For now just the HTTP response code would be fine as a response. I appreciate that this response is for the entire batch but it would at least set the scene for improved response parsing down the road.

**Comment by dparker1005** [comment]
Added in v2.3
